---
- name: FIREWALLD | Install firewalld
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ firewalld_packages }}"

- name: FIREWALLD | Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: FIREWALLD | Set Default Zone
  command: "/bin/firewall-cmd --set-default-zone={{ firewalld_default_zone | default('public') }}"
  register: result
  changed_when: 
    - "'success' in result.stdout"
    - "'ZONE_ALREADY_SET' not in result.stderr"
  notify:
    - Restart firewalld

- name: FIREWALLD | debug configuration commands
  debug:
    var: result
  when: firewalld_debug

- name: FIREWALLD | Set Zone Interfaces
  command: "/bin/firewall-cmd --zone={{ item.zone }} --change-interface={{ item.interface }} --permanent"
  with_items: "{{ firewalld_zone_interface | default([]) }}"

- name: FIREWALLD | Set Zone Sources
  firewalld:
    zone: "{{ item.zone }}" 
    source: "{{ item.source }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: "{{ item.permanent | default('true') }}" 
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_zone_source | default([]) }}"

- name: FIREWALLD | Set Service Rules
  firewalld: 
    zone: "{{ item.zone | default('public') }}"
    service: "{{ item.service }}" 
    state: "{{ item.state | default('enabled') }}" 
    permanent: "{{ item.permanent | default('true') }}" 
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_service_rules | default([]) }}"

- name: FIREWALLD | Set Port Rules
  firewalld: 
    zone: "{{ item.zone | default('public') }}"
    port: "{{ item.port }}/{{ item.protocol | default('tcp') }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: "{{ item.permanent | default('true') }}"
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_port_rules | default([]) }}"

- name: FIREWALLD | Set Rich Rules
  firewalld: 
    zone: "{{ item.zone | default('public') }}"
    rich_rule: "{{ item.rule }}" 
    state: "{{ item.state | default('enabled') }}"
    permanent: "{{ item.permanent | default('true') }}"
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_rich_rules | default([]) }}"
