---
- name: FIREWALLD | Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - "{{ ansible_distribution }}_{{ ansible_distribution_version | replace('.','_') }}.yml"
    - "{{ ansible_distribution }}_{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_version | replace('.','_') }}.yml"
    - "{{ ansible_os_family }}_{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - default.yml

- name: FIREWALLD | Install firewalld
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ firewalld_packages }}"

- name: FIREWALLD | Start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: FIREWALLD | Set Default Zone
  command: "/bin/firewall-cmd --set-default-zone={{ firewalld_default_zone | default('public') }}"
  register: result
  changed_when:
    - "'success' in result.stdout"
    - "'ZONE_ALREADY_SET' not in result.stderr"
  notify:
    - Reload firewalld

- name: FIREWALLD | debug configuration commands
  debug:
    var: result
  when: firewalld_debug is defined and firewalld_debug

- name: FIREWALLD | Set Zone Interfaces
  command: "/bin/firewall-cmd --zone={{ item.zone }} --change-interface={{ item.interface }} --permanent"
  register: result
  changed_when:
    - "'success' in result.stdout"
    - "'already bound to' not in result.stderr"
  with_items: "{{ firewalld_zone_interface | default([]) }}"
  notify:
    - Reload firewalld

- name: FIREWALLD | Set Zone Sources
  firewalld:
    zone: "{{ item.zone }}"
    source: "{{ item.source }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: "{{ item.permanent | default('true') }}"
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_zone_source | default([]) }}"
  notify:
    - Reload firewalld

- name: FIREWALLD | Set Service Rules
  firewalld:
    zone: "{{ item.zone | default('public') }}"
    service: "{{ item.service }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: "{{ item.permanent | default('true') }}"
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_service_rules | default([]) }}"
  notify:
    - Reload firewalld

- name: FIREWALLD | Set Port Rules
  firewalld:
    zone: "{{ item.zone | default('public') }}"
    port: "{{ item.port }}/{{ item.protocol | default('tcp') }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: "{{ item.permanent | default('true') }}"
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_port_rules | default([]) }}"
  notify:
    - Reload firewalld

- name: FIREWALLD | Set Rich Rules
  firewalld:
    zone: "{{ item.zone | default('public') }}"
    rich_rule: "{{ item.rule }}"
    state: "{{ item.state | default('enabled') }}"
    permanent: "{{ item.permanent | default('true') }}"
    immediate: "{{ item.immediate | default('true') }}"
  with_items: "{{ firewalld_rich_rules | default([]) }}"
  notify:
    - Reload firewalld
