---
- name: FIREWALLD | Install firewalld
  tags: [ 'configuration', 'security', 'firewalld' ]
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ firewalld_packages }}"

- name: FIREWALLD | Start firewalld
  tags: [ 'configuration', 'security', 'firewalld' ]
  service:
    name: firewalld
    state: started
    enabled: yes

- name: FIREWALLD | Set Default Zone
  tags: [ 'configuration', 'security', 'firewalld' ]
  command: "/bin/firewall-cmd --set-default-zone={{ firewalld_default_zone | default('public') }}"
  register: result
  changed_when: result.stdout == "success"
  notify:
    - Restart firewalld

- name: FIREWALLD | Set Zone Interface
  tags: [ 'configuration', 'security', 'firewalld' ]
  command: "/bin/firewall-cmd --zone={{ item.key }} --change-interface={{ item.value }} --permanent"
  with_dict: "{{ firewalld_zone_interface | default({}) }}"

- name: FIREWALLD | Set Zone Source
  tags: [ 'configuration', 'security', 'firewalld' ]
  firewalld:
    zone: "{{ item.key }}" 
    source: "{{ item.value.source | join(' ') }}"
    state: "{{ item.value.state | default('enabled') }} "
    permanent: "{{ item.value.permanent | default('true') }}" 
    immediate: "{{ item.value.immediate | default('true') }}"
  with_dict: "{{ firewalld_zone_source | default({}) }}"

- name: FIREWALLD | Set Service Rules
  tags: [ 'configuration', 'security', 'firewalld' ]
  firewalld: 
    zone: "{{ item.value.zone | default('public') }}"
    service: "{{ item.key }}" 
    state: "{{ item.value.state | default('enabled') }}" 
    permanent: "{{ item.value.permanent | default('true') }}" 
    immediate: "{{ item.value.immediate | default('true') }}"
  with_dict: "{{ firewalld_service_rules | default({}) }}"

- name: FIREWALLD | Set Port Rules
  tags: [ 'configuration', 'security', 'firewalld' ]
  firewalld: 
    zone: "{{ item.value.zone | default('public') }}"
    port: "{{ item.value.port }}/{{ item.value.protocol | default('tcp') }}"
    state: "{{ item.value.state | default('enabled') }}"
    permanent: "{{ item.value.permanent | default('true') }}"
    immediate: "{{ item.value.immediate | default('true') }}"
  with_dict: "{{ firewalld_port_rules | default({}) }}"

- name: FIREWALLD | Set Rich Rules
  tags: [ 'configuration', 'security', 'firewalld' ]
  firewalld: 
    zone: "{{ item.value.zone | default('public') }}"
    rich_rule: "{{ item.value.rule }}" 
    state: "{{ item.value.state | default('enabled') }}"
    permanent: "{{ item.value.permanent | default('true') }}"
    immediate: "{{ item.value.immediate | default('true') }}"
  with_dict: "{{ firewalld_rich_rules | default({}) }}"
