---
- name: Save iptables
  tags: [ 'services', 'security', 'firewalld' ]
  command: service iptables save

- name: Restart iptables
  tags: [ 'services', 'security', 'firewalld' ]
  service:
    name: iptables
    state: restarted

- name: Restart firewalld
  tags: [ 'services', 'security', 'firewalld' ]
  service:
    name: firewalld
    state: restarted

- name: Reload firewalld
  tags: [ 'services', 'security', 'firewalld' ]
  service:
    name: firewalld
    state: reloaded
